### ISSUE TITLE
"Learn More" link label should be changed to "View All"

### ISSUE THREAD

**Issue by himanshu201209** [NotAnother-NZ/Kensway#24]
[![Screenshot_2024-07-26_05-37-55.png](https://mrkr.io/s/66a33633ecbb9ab93c435207/2)](https://mrkr.io/s/66a33633ecbb9ab93c435207/0)

Steps to reproduce:
1) go to sectors page
2) scroll down to different sectors section
3) notice the "Learn more" link
4) compare with figma

Actual result: link label is "Learn more"

Expected result: it should be "View All"

---

**Reported by:** Vinod (vinod@na.studio)

**Source URL:** [https://kensway.webflow.io/sectors](https://kensway.webflow.io/sectors)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66a33633ecbb9ab93c43520a_e8a0725d2672d005?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 127.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by vinod-ku1989** [comment]
it is still "learn more" label for the "commercial" section. fixed for other sections.
@Himanshu201209

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66a33633ecbb9ab93c43520a?advanced=1) - 💬 **Vinod** commented:

> still not fixed for "commercial sector" section.
> it still shows "learn more"

[Reply here](https://app.marker.io/i/66a33633ecbb9ab93c43520a?advanced=1)

**Comment by himanshu201209** [comment]
Fixed

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66a33633ecbb9ab93c43520a?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
