### ISSUE TITLE
nothing happens on clicking the marker icon present on the map

### ISSUE THREAD

**Issue by himanshu201209** [NotAnother-NZ/Kensway#37]
[![Screenshot_2024-08-05_14-56-52.png](https://mrkr.io/s/66a73c1a73d4fa5cb5e01622/2)](https://mrkr.io/s/66a73c1a73d4fa5cb5e01622/0)

Steps to reproduce:
1) go to any map shown on the contact page
2) hover over marker icon
3)click

Actual result: pointer turns into hand icon but nothing happens on clicking it

Expected result: user should be redirected properly or it should not change into hand icon on hovering over it.

---

**Reported by:** Vinod (vinod@na.studio)

**Source URL:** [https://kensway.webflow.io/contact](https://kensway.webflow.io/contact)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/66a73c1a73d4fa5cb5e01625?advanced=1)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 127.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 (10.0.0)</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 641</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by Druhin13** [comment]
keeping the pointer cursor;
and redirecting to the Google map link upon user-click (on a new window)

**Comment by himanshu201209** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/66a73c1a73d4fa5cb5e01625?advanced=1) - This issue was marked as **✅ Resolved** in Marker.io
